name: Ubuntu

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dotfiles
      run: ./setup.sh
